goal=YourGoal

ic=12 # number of img clients
tc=12 # number of txt clients
mc=8 # number of img+txt clients
cncntrtn=0.5 # concentration parameter for Dirichlet distribution
c=0.25 # sampling ratio for clients
nt=8 # number of threads for parallel training
b=96 # batch size
root='' # root path of the dataset
$env:WANDB_MODE="offline"
python main.py --exp_name FedAVG --shared_param none --share_scope dataset --colearn_param none --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths ${root}data/cifar100 ${root}data/agnews ${root}data/coco ${root}data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/coco data/coco --Ks 12 12 8 --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 --E 5 --B 96 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 1 --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 --with_aux --aux_trained
python main.py --exp_name FedIoT --shared_param blocks --share_scope modality_exact --colearn_param none --algorithm fediot --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths ${root}data/cifar100 ${root}data/agnews ${root}data/coco /home/zzu/home/zzu/srs/data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512
python main.py --exp_name FedProx --shared_param none --share_scope dataset --colearn_param none --algorithm fedprox --mu 0.001 --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths ${root}data/cifar100 ${root}data/agnews ${root}data/coco ${root}data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512
python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths ${root}data/cifar100 ${root}data/agnews ${root}data/coco ${root}data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-7 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128 --pub_data_dir ${root}data/coco/all_images/  --pub_anno_path ${root}data/coco/annotations/captions_train2014.json
/home/zzu/home/zzu/srs/data
bash scripts/shiyan.sh
python main.py --exp_name FedIF_Standard --algorithm fedif --fedif_gamma 0.9 --shared_param attn --share_scope modality --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --Cs 0.25 --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 1 --use_bert_tokenizer --eval_batch_size 512 --pretrained
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Flickr30k --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data//flickr30k --Ks 12 12 8 --Cs 0.25 --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 1 --use_bert_tokenizer --eval_batch_size 512 --pretrained
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/coco data/coco --Ks 12 12 8 --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 --E 5 --B 96 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 8 --use_bert_tokenizer --pretrained --goal yl--equal_sampled --eval_batch_size 512 --with_aux --aux_trained


python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/coco data/coco --Ks 16 16 12 --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 --E 5 --B 96 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal io --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-7 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128 --pub_data_dir data/coco/all_images/  --pub_anno_path data/coco/annotations/captions_train2014.json
python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 16 16 8 --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal l --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-7 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128
python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 16 16 12 --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --C 5 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal l --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-7 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128

16 16 12
python main.py --exp_name FedIF_Standard --algorithm fedif --fedif_gamma 0.9 --shared_param attn --share_scope modality --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 16 16 8 --Cs 0.25 --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 40 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --eval_batch_size 512 --pretrained

python main.py --exp_name FedIF_Standard --algorithm fedif --fedif_gamma 0.9 --shared_param attn --share_scope modality --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --Cs 0.25 0.25 0.5 --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --eval_batch_size 512 --pretrained
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --test_size -1 --split_type diri --cncntrtn 0.5 --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal yl--equal_sampled --eval_batch_size 512 --with_aux --aux_trained --noise 1 --level_n_system 0.4 --level_n_lowerb 0.5 --level_n_upperb 0.7
python main.py --exp_name CreamFL --shared_param none --share_scope dataset --colearn_param none --algorithm creamfl --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 0.25 0.5 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 1 --use_bert_tokenizer --pretrained --goal l --equal_sampled --eval_batch_size 512 --interintra_weight 1 --kd_weight 1e-6 --num_pub_samples 500 --no_mm_contrastive --pub_batch_size 128 --pub_data_dir data/coco/all_images/  --pub_anno_path data/coco/annotations/captions_train2014.json
python main.py --exp_name FedCola --shared_param attn --share_scope modality  --colearn_param none --compensation --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --Cs 0.25  --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --eval_batch_size 512 --pretrained --algorithm fedavg --with_aux --aux_trained

python main1.py --exp_name FedIF_Standard --enable_fisher --fisher_batches 2 --fisher_clip 3 --algorithm fedif --fedif_gamma 0.8 --shared_param attn --share_scope modality --colearn_param none --compensation --with_aux --aux_trained --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --Cs 0.25 0.25 0.5  --equal_sampled --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --eval_batch_size 512 --pretrained

python main.py --exp_name FedProx --shared_param none --share_scope dataset --colearn_param none --algorithm fedprox --mu 0.001 --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Coco Coco --modalities img txt img+txt img+txt --data_paths ${root}data/cifar100 ${root}data/agnews ${root}data/coco ${root}data/coco --Ks $ic $tc $mc --test_size -1 --split_type diri --cncntrtn $cncntrtn --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs $c --E 5 --B $b --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread $nt --use_bert_tokenizer --pretrained --goal $goal --equal_sampled --eval_batch_size 512
python main.py --exp_name FedProx --shared_param none --share_scope dataset --colearn_param none --algorithm fedprox --mu 0.001 --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8  --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm  --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 0.25 0.5 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal l --equal_sampled --eval_batch_size 512
python main.py --exp_name FedAVG --shared_param none --share_scope dataset --colearn_param none --seed 1 --multi-task --datasets CIFAR100 AG_NEWS Flickr30k Coco --modalities img txt img+txt img+txt --data_paths data/cifar100 data/agnews data/flickr30k data/coco --Ks 12 12 8 --test_size -1 --split_type diri --cncntrtn 0.1 --model_name mome_small_patch16 --resize 224 --imnorm --algorithm fedavg --eval_type global --eval_every 1 --eval_metrics acc1 --R 30 --Cs 0.25 0.25 0.5 --E 5 --B 112 --beta1 0 --optimizer AdamW --lr 1e-4 --lr_decay 0.99 --lr_decay_step 1 --criterion CrossEntropyLoss --num_thread 2 --use_bert_tokenizer --pretrained --goal l --equal_sampled --eval_batch_size 512 --K 32 --robust_seed 1 --noise 2 --level_n_system 0.3 --level_n_lowerb 0.2 --level_n_upperb 0.6 --level_n_mean 0.0 --level_n_std 0.1
